### ISSUE TITLE
session.RecvMessage 中，login/game中的任意一个， 就把client连接断开？

### ISSUE THREAD

**Issue by ruandao** [panshiqu/framework#2]
https://github.com/panshiqu/framework/blob/af6c9520d6a3fb0386b0c93d1cdcd19bec54d457/proxy/session.go#L115-L136

为什么这么设计呢？

**Comment by panshiqu** [comment]
login/game业务返回错误也都只是封包发往客户端，只有在套接字读写失败（断开）的时候才会触发break，此时断开因客户端而创建的所有连接也没什么不好，这样反而很方便，连接断开触发CloseSession，一劳永逸，客户端收到连接断开，会重连的，这时他甚至会连接到另一个proxy也有可能，重连成本并不高，只要游戏不跪，用户只会看到正在重连的提示，紧接着就恢复了
