### ISSUE TITLE
为什么,这里 s.connections 要置为nil, 如果不置为nil的化,好像很多地方,都不用判断是否是nil

### ISSUE THREAD

**Issue by ruandao** [panshiqu/framework#3]
https://github.com/panshiqu/framework/blob/af6c9520d6a3fb0386b0c93d1cdcd19bec54d457/network/server.go#L52-L60

**Comment by panshiqu** [comment]
你不觉得我俨然把它当成服务器已关闭的标志来用了吗？当初设计成"调用Stop将等待所有Goroutines退出才返回"，所以Stop之后不能再因新连接起新Goroutines，否则将无限等待新Goroutines退出，因为 go s.handleConn(conn) 所以这是存在可能的
