### ISSUE TITLE
感觉这个方法应该换下

### ISSUE THREAD

**Issue by ruandao** [panshiqu/framework#4]
https://github.com/panshiqu/framework/blob/af6c9520d6a3fb0386b0c93d1cdcd19bec54d457/proxy/session.go#L139-L167

这个

    atomic.StoreInt32(&s.status, define.KeepAliveWarn)
换成：

    atomic.CompareAndSwapInt32(&s.status, define.KeepAliveSafe, define.KeepAliveWarn)

防止客户端收到报文，刚设定为KeepAliveSafe， 然后就被替换成KeepAliveWarn

**Comment by panshiqu** [comment]
你提的是一个无论如何都无法实现的想法吧？独立的 KeepAlive Goroutine，它无法知道 s.status 是刚刚还是好久之前收到客户端消息而被设置成 KeepAliveSafe。那怕刚收到消息只要时间到期也会标记为 KeepAliveWarn，这个操作没有代价的。毕竟下个周期也才尝试发送心跳包。

`// CompareAndSwapInt32 executes the compare-and-swap operation for an int32 value.
func CompareAndSwapInt32(addr *int32, old, new int32) (swapped bool)`
逻辑执行到这里，s.status 的值只能是 KeepAliveSafe，如此调用就毫无意义啦
