### ISSUE TITLE
一个疑问，内部节点，是否需要保活

### ISSUE THREAD

**Issue by ruandao** [panshiqu/framework#5]
代理节点，到各个服务器节点的连接，是否需要保活？

**Comment by panshiqu** [comment]
保活如果有总是好的，谁保活谁就有主动权，它解决在不知情时对方死掉自己不会及时释放资源的场景，遗憾的是内部服务器之间我并未实现保活，回忆当初理由可能是：自己人比较放心，框架定位就是中小型，更何况直到现在我都没有把它用在生产环境...

其实关于这个小框架，我曾经写过[博客](https://blog.csdn.net/panshiqu/article/details/74572133)，不知道你在提 issues 之前有没有看到过，我已更新 README.md
